In [14]:
# Covering torch NN and torch optim module

In [1]:
import torch
import torch.nn as nn


In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out
    

In [3]:
features = torch.rand(10, 5)
model = Model(features.shape[1])


In [4]:
# Forward pass
output = model(features)
print("Output shape:", output.shape)  # Should be (10, 1)

Output shape: torch.Size([10, 1])


In [5]:
model.linear.weight

Parameter containing:
tensor([[-0.2768,  0.2725,  0.3790, -0.0341, -0.0696]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([0.1503], requires_grad=True)

In [8]:
from torchinfo import summary

In [9]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
class Model(nn.Module):
    def __init__(self, in_features, hidden_features):
        super().__init__()
        self.linear1 = nn.Linear(in_features, hidden_features)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out
    

In [11]:
X = torch.rand(10, 5)
model = Model(X.shape[1], 3)


In [12]:
model(X)

tensor([[0.5621],
        [0.5621],
        [0.5701],
        [0.5621],
        [0.5621],
        [0.5621],
        [0.5621],
        [0.5697],
        [0.5707],
        [0.5621]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.weight

Parameter containing:
tensor([[-0.1951,  0.0056,  0.0056, -0.1856, -0.3911],
        [ 0.2897,  0.3537,  0.0105,  0.1022, -0.2493],
        [-0.2470, -0.3426, -0.1535, -0.0133, -0.1995]], requires_grad=True)

In [15]:
class Model(nn.Module):

    def __init__(self, in_features, hidden_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features, hidden_features),
            nn.ReLU(),
            nn.Linear(hidden_features, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x) 


In [16]:
x = torch.rand(10, 5)
model = Model(x.shape[1], 3)
model(x)

tensor([[0.4729],
        [0.4452],
        [0.4563],
        [0.4630],
        [0.4729],
        [0.4384],
        [0.4729],
        [0.4509],
        [0.4729],
        [0.4715]], grad_fn=<SigmoidBackward0>)