In [1]:
import torch

In [2]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 4, 5])

In [3]:
print(tensor1)
print(tensor2)

tensor([1, 2, 3])
tensor([2, 4, 5])


In [6]:
dotP = (tensor1.float() * tensor2.float()).mean()

In [7]:
dotP

tensor(8.3333)

In [9]:
mmul = torch.matmul(tensor1, tensor2)
print(mmul)

tensor(25)


matrix x vector

In [13]:
t1 = torch.randn(3, 4)
t2 = torch.randn(4)
mmul = torch.matmul(t1, t2)

In [14]:
mmul

tensor([-1.8409, -2.0042, -1.3476])

In [ ]:
# batched matrix x broadcasted vector
tensor1 = torch.tensor([10, 3, 4])
tensor2 = torch.tensor([4])
mmul = torch.matmul(tensor1, tensor2)

In [19]:
mmul

tensor([[-0.1758, -0.0331, -0.1979],
        [-0.6911, -0.7767, -0.0954],
        [ 0.4253,  0.4184, -0.4157],
        [-0.2815, -0.7218, -0.2318],
        [ 0.0574,  0.0216, -0.7557],
        [ 0.6730,  0.5298, -0.0216],
        [-0.3174,  0.2583,  0.0891],
        [-0.7220, -0.0329, -0.2232],
        [-0.1926,  0.1143,  0.3212],
        [-0.4037, -0.6085,  0.6974]])

In [ ]:

# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

In [23]:
x = (0.6 > 0.5).float()
print(x)

AttributeError: 'bool' object has no attribute 'float'